version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - exhaustive
    - goconst
    - gomoddirectives
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
  settings:
    sloglint:
      no-mixed-args: true
      context: scope
      static-msg: true
      key-naming-case: snake
  exclusions:
    rules:
      - text: '(slog|log)\.\w+'
        linters:
          - noctx
    generated: lax
    presets:
      - common-false-positives
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax