/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プロフィールを取得する
         * @description プロフィールを返す。
         *     存在しない場合は 404 を返す。
         */
        get: operations["getMe"];
        /**
         * プロフィールを更新する
         * @description プロフィール全体を上書き更新する。
         *     存在しない場合は 404 を返す。
         */
        put: operations["updateMe"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログインする
         * @description 資格情報を検証し HttpOnly Cookie を発行します。
         *     レスポンスボディは空となります。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログアウトする
         * @description 現在のセッション（RT）を `Session.revoke()` で失効させ、Cookie を削除します。
         *     他の端末のセッションには影響しません。全セッション解除は `DELETE /auth/sessions` を使用してください。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 全RTを失効させる
         * @description `SessionRepository.RevokeAll()` により該当ユーザーの全 RT を失効させます。
         *     既発行の AT は TTL（一般: 15分、管理者: 5分）内で自然失効します。
         */
        delete: operations["revokeAllSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * トークンをリフレッシュする
         * @description RT Cookie を検証し、`Session.rotate(newHash)` により新しい AT と RT を発行します（ローテーション）。
         *     **リプレイ検知**: 失効済み（REVOKED）の RT でリクエストされた場合、盗難と判断し
         *     `SessionRepository.RevokeAll()` により全 RT を失効させます。AT は TTL 内で自然失効します。このとき 401 を返します。
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Identityを登録する
         * @description メールアドレスとパスワードで Identity を新規登録します。
         *     メールアドレスが既に使用済みの場合は 409 Conflict を返します。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * パスワードをリセットする
         * @description 新しいパスワードを送信し、passwordHash を更新します。
         *     成功時は該当ユーザーの全 Session を即時 Revoke します（`PasswordReset` イベント）。
         */
        put: operations["resetPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * メールアドレスを変更する
         * @description 新しいメールアドレスを送信し、email を更新します。
         *     新しいメールアドレスが既に使用済みの場合は 409 Conflict を返します。
         */
        put: operations["changeEmail"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 記事を検索・一覧する
         * @description キーワード、タグ、年、プラットフォームで記事を絞り込み、publishedAt 降順で返す。
         *     `q` 指定時は Kagome でトークン化し tokens に対して完全一致フィルタを適用する。
         *     トップページの最新記事表示（limit=5）もこのエンドポイントを使用する。
         */
        get: operations["listArticles"];
        put?: never;
        /**
         * 記事を手動追加する
         * @description API がない媒体の記事を管理画面から手動で登録する。
         *     `tokens` はアプリケーション層が `title` を Kagome でトークン化して生成するため、リクエストに含めない。
         */
        post: operations["createArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/meta/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * タグ一覧を取得する
         * @description 全タグとそれぞれのアクティブ記事数を返す。Articles ページのタグクラウド表示に使用。
         *     count 降順。
         */
        get: operations["listArticleTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/meta/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 検索サジェストを取得する
         * @description ユーザーの入力に対して、タグ・トークン・タイトルの候補を最大 10 件返す。
         *     前方一致 → あいまいマッチ（レーベンシュタイン距離 ≤ 1）の順で優先。
         *     フロント側は debounce 150ms で呼び出す。
         */
        get: operations["suggestArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{externalId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 対向システムが発行した記事の外部 ID。 */
                externalId: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 記事を手動更新する
         * @description 手動追加した記事を管理画面から全上書き更新する（PUT）。
         *     `externalId` と `platform` は変更不可。`tokens` はアプリケーション層が再生成する。
         */
        put: operations["updateArticle"];
        post?: never;
        /**
         * 記事を手動削除する
         * @description 管理画面から記事を論理削除する。
         */
        delete: operations["deleteArticle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description エラー情報の標準フォーマット (RFC 9457) */
        ProblemDetails: {
            /**
             * Format: uri-reference
             * @description エラーの種類を識別するURIリファレンス。
             * @default about:blank
             * @example https://me.app/probs/invalidParameters
             */
            type: string;
            /**
             * @description エラーの種類の簡潔な概要（人間向け、言語化可能）。
             * @example Your request parameters didn't validate.
             */
            title: string;
            /**
             * @description この問題の発生に対してオリジンサーバーによって生成されたHTTPステータスコード。
             * @example 400
             */
            status: number;
            /**
             * @description この問題の発生に関する詳細な説明（人間向け）。
             * @example The 'emailAddress' field must be a valid email address.
             */
            detail?: string;
            /**
             * Format: uri-reference
             * @description エラーが発生した特定のリソースを識別するURIリファレンス。
             * @example /api/messages/550e8400-e29b-41d4-a716-446655440000
             */
            instance?: string;
            /** @description バリデーションエラーの詳細（拡張フィールド）。 */
            invalidParams?: components["schemas"]["InvalidParam"][];
        };
        InvalidParam: {
            /**
             * @description エラーが発生したフィールド名。
             * @example emailAddress
             */
            name: string;
            /**
             * @description エラーの理由。
             * @example must be a valid email address
             */
            reason: string;
        };
        /**
         * @description 記事の公開プラットフォーム。
         * @example qiita
         * @enum {string}
         */
        Platform: "qiita" | "zenn" | "mochiya" | "note";
        ArticleItem: {
            /** @example b0adacee33b2774d7089 */
            externalId: string;
            /** @example サトシ:「行け!!ピカチュウ!!」はFactory Methodだったのか...。 */
            title: string;
            /**
             * Format: uri
             * @example https://qiita.com/umekikazuya/items/b0adacee33b2774d7089
             */
            url: string;
            platform: components["schemas"]["Platform"];
            /**
             * Format: date-time
             * @description 公開日時。存在しない場合は省略。
             * @example 2025-04-14T00:00:00Z
             */
            publishedAt?: string;
            /**
             * @example [
             *       "design-pattern",
             *       "factory-method",
             *       "PHP"
             *     ]
             */
            tags: string[];
        };
        ArticleListResponse: {
            /** @description publishedAt 降順。 */
            articles: components["schemas"]["ArticleItem"][];
            /**
             * @description 次ページのカーソル。省略された場合は最終ページ。
             * @example eyJsYXN0X2tl...
             */
            nextCursor?: string;
        };
        ArticleTagItem: {
            /** @example SOLID */
            name: string;
            /**
             * @description そのタグが付いたアクティブ記事の数。
             * @example 5
             */
            count: number;
        };
        ArticleTagListResponse: {
            /** @description count 降順。 */
            tags: components["schemas"]["ArticleTagItem"][];
        };
        ArticleTagSuggestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tag";
            /**
             * @description タグ名。
             * @example SOLID
             */
            value: string;
            /**
             * @description そのタグが付いたアクティブ記事の数。
             * @example 5
             */
            count: number;
        };
        ArticleTokenSuggestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "token";
            /**
             * @description トークン文字列。
             * @example 設計
             */
            value: string;
            /**
             * @description そのトークンが出現するアクティブ記事の数。
             * @example 8
             */
            count: number;
        };
        ArticleTitleSuggestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "title";
            /**
             * @description 記事タイトル。
             * @example 【SOLID原則】犬に「飛べ！」と言っちゃだめです。
             */
            value: string;
            /**
             * @description 記事の外部 ID。
             * @example a8751e422bf198cde70f
             */
            externalId: string;
        };
        ArticleSuggestionItem: components["schemas"]["ArticleTagSuggestion"] | components["schemas"]["ArticleTokenSuggestion"] | components["schemas"]["ArticleTitleSuggestion"];
        ArticleSuggestResponse: {
            suggestions: components["schemas"]["ArticleSuggestionItem"][];
        };
        ArticleCreateRequest: {
            /** @example article-001 */
            externalId: string;
            /** @example モチヤブログの記事タイトル */
            title: string;
            /**
             * Format: uri
             * @example https://www.mochiya.ad.jp/blog/article-001
             */
            url: string;
            platform: components["schemas"]["Platform"];
            /**
             * Format: date-time
             * @description 外部記事の公開日時。省略可。
             * @example 2025-06-01T00:00:00Z
             */
            publishedAt?: string;
            /**
             * Format: date-time
             * @description 外部記事の更新日時。省略可。
             * @example 2025-07-01T00:00:00Z
             */
            articleUpdatedAt?: string;
            /**
             * @description タグ一覧。省略可。
             * @example [
             *       "drupal",
             *       "cms"
             *     ]
             */
            tags?: string[];
        };
        /**
         * @description PUT セマンティクス（全量上書き）。省略したオプショナルフィールドはクリアされる。
         *     例: `publishedAt` を省略すると null にクリアされる。`tags` を省略すると空配列になる。
         */
        ArticleUpdateRequest: {
            /** @example モチヤブログの記事タイトル（改訂版） */
            title: string;
            /**
             * Format: uri
             * @example https://www.mochiya.ad.jp/blog/article-001
             */
            url: string;
            /**
             * Format: date-time
             * @description 外部記事の公開日時。省略するとクリアされる。
             * @example 2025-06-01T00:00:00Z
             */
            publishedAt?: string;
            /**
             * Format: date-time
             * @description 外部記事の更新日時。省略するとクリアされる。
             * @example 2025-07-01T00:00:00Z
             */
            articleUpdatedAt?: string;
            /**
             * @description タグ一覧。省略すると空配列にクリアされる。
             * @example [
             *       "drupal",
             *       "cms",
             *       "migration"
             *     ]
             */
            tags?: string[];
        };
        LoginRequest: {
            /** Format: email */
            emailAddress: string;
            /** Format: password */
            password: string;
        };
        RegisterRequest: {
            /** Format: email */
            emailAddress: string;
            /** Format: password */
            password: string;
        };
        PasswordResetRequest: {
            /** Format: password */
            newPassword: string;
        };
        ChangeEmailRequest: {
            token: string;
            /** Format: email */
            newEmailAddress: string;
        };
        MeSkillGroup: {
            /** @example Frontend */
            category: string;
            /**
             * @example [
             *       "React",
             *       "Next.js",
             *       "TypeScript",
             *       "Lit"
             *     ]
             */
            items: string[];
            /** @example 0 */
            sortOrder: number;
        };
        MeCertification: {
            /** @example GCP Associate Cloud Engineer */
            name: string;
            /**
             * @description 発行元。未設定の場合は省略。
             * @example Google Cloud
             */
            issuer?: string;
            /**
             * @description 取得年。必須。
             * @example 2025
             */
            year: number;
            /**
             * @description 取得月。未設定の場合は省略。
             * @example 6
             */
            month?: number;
        };
        MeExperience: {
            /** @example モチヤ株式会社 */
            company: string;
            /**
             * Format: uri
             * @description 企業サイト。未設定の場合は省略。
             * @example https://www.mochiya.ad.jp/
             */
            url?: string;
            /**
             * @description 在籍開始年。必須。
             * @example 2022
             */
            startYear: number;
            /**
             * @description 在籍終了年。在職中の場合は省略。
             * @example 2024
             */
            endYear?: number;
        };
        MeLink: {
            /** @example github */
            platform: string;
            /**
             * Format: uri
             * @example https://github.com/umekikazuya
             */
            url: string;
            /**
             * @description 表示ラベル。未設定の場合は省略。
             * @example GitHub
             */
            label?: string;
        };
        MeRequest: {
            /** @example Kazuya Umeki */
            displayName: string;
            /** @example 梅木和弥 */
            displayJa?: string;
            /** @example Web Creator */
            role?: string;
            /** @example Fukuoka, Japan */
            location?: string;
            skills?: components["schemas"]["MeSkillGroup"][];
            certifications?: components["schemas"]["MeCertification"][];
            experiences?: components["schemas"]["MeExperience"][];
            links?: components["schemas"]["MeLink"][];
            /**
             * @example [
             *       "Mr.Children",
             *       "CUTIE STREET"
             *     ]
             */
            likes?: string[];
        };
        /** @description プロフィール全体。`MeRequest` と対称な形をとる。 */
        MeResponse: {
            /** @example Kazuya Umeki */
            displayName: string;
            /**
             * @description 未設定の場合は省略。
             * @example 梅木 和弥
             */
            displayJa?: string;
            /** @example Web Creator */
            role: string;
            /** @example Fukuoka, Japan */
            location: string;
            skills: components["schemas"]["MeSkillGroup"][];
            certifications: components["schemas"]["MeCertification"][];
            experiences: components["schemas"]["MeExperience"][];
            links: components["schemas"]["MeLink"][];
            /**
             * @example [
             *       "Mr.Children",
             *       "CUTIE STREET"
             *     ]
             */
            likes: string[];
            /**
             * Format: date-time
             * @example 2026-03-22T10:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-03-22T10:00:00Z
             */
            updatedAt: string;
        };
    };
    responses: {
        /** @description 不正なリクエスト (RFC 9457) */
        BadRequest: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 認証エラー (RFC 9457) */
        Unauthorized: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 権限不足 (RFC 9457) */
        Forbidden: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description リソース不在 (RFC 9457) */
        NotFound: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 競合 (RFC 9457) */
        Conflict: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description レート制限超過 (RFC 9457) */
        TooManyRequests: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description サーバーエラー (RFC 9457) */
        InternalServerError: {
            headers: {
                "X-Request-ID": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description 1ページあたりの最大取得件数。 */
        MaxResults: number;
        /** @description 次のページを取得するためのトークン。 */
        PageToken: string;
        /** @description リクエストを一意に識別するID（ログ追跡用）。 */
        XRequestId: string;
        /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
        XRequestedWith: "XMLHttpRequest";
    };
    requestBodies: never;
    headers: {
        /** @description リクエストを一意に識別する ID (ログ追跡用) */
        XRequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 成功。Cookies がセットされます。 */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功。 */
            204: {
                headers: {
                    /** @description 有効期限切れの Cookies (meAccessToken, meRefreshToken) を返却して削除を促します。 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeAllSessions: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功。全RTが失効しました。 */
            204: {
                headers: {
                    /** @description 有効期限切れの Cookies を返却して削除を促します。 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功。新しい Cookies がセットされます。 */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 成功。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description 成功。全セッションが失効します。 */
            204: {
                headers: {
                    /** @description 有効期限切れの Cookies を返却して削除を促します。 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    changeEmail: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeEmailRequest"];
            };
        };
        responses: {
            /** @description 成功。 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listArticles: {
        parameters: {
            query?: {
                /** @description キーワード。Kagome でトークン化し tokens に対して完全一致フィルタを適用。同義語辞書で正規化。 */
                q?: string;
                /** @description タグフィルタ。複数指定で AND 条件。 */
                tag?: string[];
                /** @description 公開年フィルタ。正の整数。 */
                year?: number;
                /** @description プラットフォームフィルタ。 */
                platform?: components["schemas"]["Platform"];
                /** @description 取得件数。デフォルト 50、最大 100。 */
                limit?: number;
                /** @description ページネーション用カーソル。前回レスポンスの nextCursor を指定。 */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createArticle: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listArticleTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleTagListResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    suggestArticles: {
        parameters: {
            query: {
                /** @description 検索入力。1 文字以上。 */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleSuggestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateArticle: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path: {
                /** @description 対向システムが発行した記事の外部 ID。 */
                externalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleUpdateRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteArticle: {
        parameters: {
            query?: never;
            header: {
                /** @description CSRF 対策用のカスタムヘッダ。値は `XMLHttpRequest` 固定。 */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path: {
                /** @description 対向システムが発行した記事の外部 ID。 */
                externalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
