name: CD

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.DEPLOY_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Go
        uses: actions/setup-go@v6.5.0
        with:
          go-version-file: "backend/.go-version"
          cache-dependency-path: "backend/go.sum"

      - name: Tidy backend dependencies
        working-directory: ./backend
        run: go mod tidy

      - name: Build backend application
        working-directory: ./backend
        run: |
          CGO_ENABLED=0 \
          GOOS=linux \
          GOARCH=arm64 \
          go build -o bootstrap ./cmd/api/lambda && \
          zip ../deployment.zip bootstrap

      - name: Deploy backend application to Lambda
        env:
          FUNCTION_NAME: ${{ secrets.API_FUNCTION_NAME }}
        run: |
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://deployment.zip

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/setup@v2.0.2
        with:
          version: "11.21.0"
          runtime: node@24
          cache: true
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @me/public build
        env:
          VITE_GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
      - run: pnpm --filter @me/public inject:meta
        env:
          API_ORIGIN: ${{ secrets.API_ORIGIN }}
      - uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.DEPLOY_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          aws s3 sync \
            frontend/public/dist/ s3://${{ secrets.BUCKET_NAME }}/ \
            --cache-control "public,max-age=31536000,immutable" \
            --exclude "*.html"
          aws s3 cp frontend/public/dist/ s3://${{ secrets.BUCKET_NAME }}/ \
            -recursive \
            --cache-control "public,max-age=0,must-revalidate" \
            --exclude "*" --include "*.html"
      - run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html"